accelerator: null
accumulate_grad_batches: null
amp_backend: native
amp_level: null
auto_lr_find: false
auto_scale_batch_size: false
auto_select_gpus: false
avg_reward_len: 100
batch_size: 128
benchmark: false
check_val_every_n_epoch: 1
checkpoint_callback: null
clip_ratio: 0.2
default_root_dir: null
detect_anomaly: false
deterministic: false
devices: null
enable_checkpointing: true
enable_model_summary: true
enable_progress_bar: true
env: WordleEnv100-v0
evaluate: false
fast_dev_run: false
flush_logs_every_n_steps: null
gamma: 0.99
gpus: null
gradient_clip_algorithm: null
gradient_clip_val: null
hidden_size: 512
ipus: null
lam: 0.95
limit_predict_batches: 1.0
limit_test_batches: 1.0
limit_train_batches: 1.0
limit_val_batches: 1.0
log_every_n_steps: 50
log_gpu_memory: null
logger: true
lr_actor: 0.0003
lr_critic: 0.001
max_episode_len: 1000
max_epochs: null
max_steps: -1
max_time: null
min_epochs: null
min_steps: null
move_metrics_to_cpu: false
multiple_trainloader_mode: max_size_cycle
n_hidden: 2
nb_optim_iters: 4
network_name: SumChars
num_nodes: 1
num_processes: 1
num_sanity_val_steps: 2
overfit_batches: 0.0
plugins: null
precision: 32
prepare_data_per_node: null
prob_cheat: 0.05
prob_play_lost_word: 0
process_position: 0
profiler: null
progress_bar_refresh_rate: null
reload_dataloaders_every_epoch: false
reload_dataloaders_every_n_epochs: 0
replace_sampler_ddp: true
resume_from_checkpoint: null
seed: 123
steps_per_epoch: 2048
stochastic_weight_avg: false
strategy: null
sync_batchnorm: false
terminate_on_nan: null
tpu_cores: null
track_grad_norm: -1
val_check_interval: 1.0
weight_decay: 0.0
weights_save_path: null
weights_summary: top
